services:
  web-server:
    build:
      dockerfile: DockerFile
      context: .
    restart: always
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - "8080:80"
  mariadb-server:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./mariadb-data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
volumes:
  mysql-data:
